import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

type PluginSpec = {
	id: string;
	manifestImport: string;
	manifestName: string;
	loadImports?: Array<{ name: string; from: string }>;
	load: string;
};

const PLUGINS: PluginSpec[] = [
	{
		id: 'hint.user',
		manifestImport: './user/manifest',
		manifestName: 'userManifest',
		loadImports: [{ name: 'loadUserPluginModule', from: '../user-plugin' }],
		load: `{
\t\t\tcontent: () => loadUserPluginModule(),
\t\t\tbackground: () => loadUserPluginModule(),
\t\t}`,
	},
	{
		id: 'hint.whichKey',
		manifestImport: './which-key/manifest',
		manifestName: 'whichKeyManifest',
		load: `{
\t\t\tcontent: () => import('./which-key/content'),
\t\t}`,
	},
];

const parseList = (value?: string): string[] =>
	(value ?? '')
		.split(/[,\s]+/)
		.map((entry) => entry.trim())
		.filter(Boolean);

const allowList = parseList(process.env.VIFHINT_PLUGINS);
const disableList = parseList(process.env.VIFHINT_DISABLE_PLUGINS);

if (allowList.length > 0 && disableList.length > 0) {
	console.error('[plugins] Set only one of VIFHINT_PLUGINS or VIFHINT_DISABLE_PLUGINS.');
	process.exit(1);
}

const enabled =
	allowList.length > 0
		? PLUGINS.filter((plugin) => allowList.includes(plugin.id))
		: PLUGINS.filter((plugin) => !disableList.includes(plugin.id));

const importLines = new Set<string>();
importLines.add("import type { PluginDefinition } from './types';");

for (const plugin of enabled) {
	importLines.add(`import { manifest as ${plugin.manifestName} } from '${plugin.manifestImport}';`);
	if (plugin.loadImports) {
		for (const entry of plugin.loadImports) {
			importLines.add(`import { ${entry.name} } from '${entry.from}';`);
		}
	}
}

const entries = enabled
	.map(
		(plugin) => `\t{
\t\tmanifest: ${plugin.manifestName},
\t\tload: ${plugin.load},
\t},`,
	)
	.join('\n');

const output = `// This file is generated by scripts/generate-plugin-registry.ts.
// Do not edit by hand.

${Array.from(importLines).sort().join('\n')}

export const pluginRegistry: PluginDefinition[] = [
${entries}
];
`;

const outputPath = resolve('src/plugins/registry.generated.ts');
writeFileSync(outputPath, output, 'utf8');
console.log(`[plugins] Wrote ${outputPath}`);
